import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
import { CurrencyProvider } from "@/context/currencyContext";
import type { Metadata } from "next";
import { Montserrat } from 'next/font/google';
import "./globals.css";

const montserrat = Montserrat({
  subsets: ['latin'], 
  variable: '--font-montserrat',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], 
});

export const metadata: Metadata = {
  title: "Ravan Real Estate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CurrencyProvider> 
        <body className={`${montserrat.variable} antialiased`}>
          <NavBar />
          {children}
          <Footer />
        </body>
      </CurrencyProvider>
    </html>
  );
}