import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
import { CurrencyProvider } from "@/context/currencyContext"; 
import type { Metadata } from "next";
import "@/app/globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CurrencyProvider> {/* Wrap everything with CurrencyProvider */}
        <body
          
        >
          
          {children}
          <Footer />
        </body>
      </CurrencyProvider>
    </html>
  );
}
